spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:local
    username: sa
    password: 
    driver-class-name: org.h2.Driver
      
properties:
  comment: License created with Local confugration